-- MySQL Script generated by MySQL Workbench
-- Sun Jul  6 11:57:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`administracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administracao` (
  `id` INT NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `razaoSocial` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `idAdministracao` INT NOT NULL,
  PRIMARY KEY (`id`, `idAdministracao`),
  INDEX `fk_paciente_administracao_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_administracao`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `mydb`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profissionalSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profissionalSaude` (
  `id` INT NOT NULL,
  `idAdministracao` INT NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `dataContratacao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profissionalSaude_administracao1_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_profissionalSaude_administracao1`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `mydb`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `profissionalSaude_id` INT NOT NULL,
  `crm` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `dataInscricao` VARCHAR(10) NOT NULL,
  `especialidade` INT NOT NULL,
  INDEX `fk_medico_profissionalSaude1_idx` (`profissionalSaude_id` ASC) VISIBLE,
  PRIMARY KEY (`profissionalSaude_id`),
  CONSTRAINT `fk_medico_profissionalSaude1`
    FOREIGN KEY (`profissionalSaude_id`)
    REFERENCES `mydb`.`profissionalSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfermeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enfermeiro` (
  `idProfissionalSaude` INT NOT NULL,
  `coren` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `dataEmissao` VARCHAR(10) NOT NULL,
  `tipo` INT NOT NULL,
  INDEX `fk_table1_profissionalSaude1_idx` (`idProfissionalSaude` ASC) VISIBLE,
  PRIMARY KEY (`idProfissionalSaude`),
  CONSTRAINT `fk_table1_profissionalSaude1`
    FOREIGN KEY (`idProfissionalSaude`)
    REFERENCES `mydb`.`profissionalSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`farmaceutico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`farmaceutico` (
  `idProfissionalSaude` INT NOT NULL,
  `crf` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `categoriaProfissional` INT NOT NULL,
  `dataConclusao` VARCHAR(10) NOT NULL,
  `dataEspedicao` VARCHAR(10) NOT NULL,
  INDEX `fk_table2_profissionalSaude1_idx` (`idProfissionalSaude` ASC) VISIBLE,
  PRIMARY KEY (`idProfissionalSaude`),
  CONSTRAINT `fk_table2_profissionalSaude1`
    FOREIGN KEY (`idProfissionalSaude`)
    REFERENCES `mydb`.`profissionalSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anamnese` (
  `id` INT NOT NULL,
  `diabetes` TINYINT NULL,
  `hipertensao` TINYINT NULL,
  `hipotensao` TINYINT NULL,
  `tabagismo` TINYINT NULL,
  `epilepsia` TINYINT NULL,
  `proteseDentaria` TINYINT NULL,
  `problemasRespitatorios` TINYINT NULL,
  `anotacoesRespiratorias` VARCHAR(100) NULL,
  `cirurgias` TINYINT NULL,
  `anotacoesCirurgias` VARCHAR(100) NULL,
  `exerciciosFisicos` TINYINT NULL,
  `frequenciaExercicios` INT NULL,
  `alcool` TINYINT NULL,
  `frequenciaAlcool` INT NULL,
  `alergiaMedicacao` TINYINT NULL,
  `anotacoesAlergiasMedicamento` VARCHAR(10) NULL,
  `alergiaAlimento` TINYINT NULL,
  `anotacoesAlergiaAlimento` VARCHAR(100) NULL,
  `tratamentoAtual` TINYINT NULL,
  `anotacoesTratamento` VARCHAR(100) NULL,
  `marcaPasso` TINYINT NULL,
  `medicamentoContinuo` TINYINT NULL,
  `anotacoesMedicamentoContinuo` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prontuario` (
  `id` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  `idAnamnese` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prontuario_paciente1_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_prontuario_anamnese1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_prontuario_paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prontuario_anamnese1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `mydb`.`anamnese` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suprimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suprimento` (
  `id` INT NOT NULL,
  `idAdministracao` INT NOT NULL,
  `tipo` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `quantEstoque` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suprimento_administracao1_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_suprimento_administracao1`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `mydb`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agenda` (
  `id` INT NOT NULL,
  `idMedico` INT NOT NULL,
  `idPaciente` INT NULL,
  `data` VARCHAR(10) NOT NULL,
  `hora` VARCHAR(5) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agenda_medico1_idx` (`idMedico` ASC) VISIBLE,
  INDEX `fk_agenda_paciente1_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `mydb`.`medico` (`profissionalSaude_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `idAgenda` INT NOT NULL,
  `idProntuario` INT NOT NULL,
  `queixa` VARCHAR(150) NOT NULL,
  `sintomas` VARCHAR(150) NOT NULL,
  `diagnostico` VARCHAR(150) NOT NULL,
  `prescricao` VARCHAR(150) NOT NULL,
  INDEX `fk_consulta_agenda1_idx` (`idAgenda` ASC) VISIBLE,
  PRIMARY KEY (`idAgenda`),
  INDEX `fk_consulta_prontuario1_idx` (`idProntuario` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_agenda1`
    FOREIGN KEY (`idAgenda`)
    REFERENCES `mydb`.`agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_prontuario1`
    FOREIGN KEY (`idProntuario`)
    REFERENCES `mydb`.`prontuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leito` (
  `id` INT NOT NULL,
  `tipoLeito` INT NOT NULL,
  `numero` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` TINYINT NOT NULL,
  `idAdministracao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_leito_administracao1_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_leito_administracao1`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `mydb`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`internacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`internacao` (
  `id` INT NOT NULL,
  `idConsulta` INT NOT NULL,
  `idMedico` INT NOT NULL,
  `idLeito` INT NOT NULL,
  `idProntuario` INT NOT NULL,
  `status` TINYINT NOT NULL,
  `observacoes` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_internacao_consulta1_idx` (`idConsulta` ASC) VISIBLE,
  INDEX `fk_internacao_medico1_idx` (`idMedico` ASC) VISIBLE,
  INDEX `fk_internacao_leito1_idx` (`idLeito` ASC) VISIBLE,
  INDEX `fk_internacao_prontuario1_idx` (`idProntuario` ASC) VISIBLE,
  CONSTRAINT `fk_internacao_consulta1`
    FOREIGN KEY (`idConsulta`)
    REFERENCES `mydb`.`consulta` (`idAgenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internacao_medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `mydb`.`medico` (`profissionalSaude_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internacao_leito1`
    FOREIGN KEY (`idLeito`)
    REFERENCES `mydb`.`leito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internacao_prontuario1`
    FOREIGN KEY (`idProntuario`)
    REFERENCES `mydb`.`prontuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historicoInternacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historicoInternacao` (
  `id` INT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `procedimento` VARCHAR(100) NOT NULL,
  `quant` INT NULL,
  `anotacoes` VARCHAR(150) NULL,
  `idInternacao` INT NOT NULL,
  `idSuprimento` INT NOT NULL,
  `idEnfermeiro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historicoInternacao_internacao1_idx` (`idInternacao` ASC) VISIBLE,
  INDEX `fk_historicoInternacao_suprimento1_idx` (`idSuprimento` ASC) VISIBLE,
  INDEX `fk_historicoInternacao_enfermeiro1_idx` (`idEnfermeiro` ASC) VISIBLE,
  CONSTRAINT `fk_historicoInternacao_internacao1`
    FOREIGN KEY (`idInternacao`)
    REFERENCES `mydb`.`internacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historicoInternacao_suprimento1`
    FOREIGN KEY (`idSuprimento`)
    REFERENCES `mydb`.`suprimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historicoInternacao_enfermeiro1`
    FOREIGN KEY (`idEnfermeiro`)
    REFERENCES `mydb`.`enfermeiro` (`idProfissionalSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimentoSuprimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimentoSuprimento` (
  `id` INT NOT NULL,
  `idFarmaceutico` INT NOT NULL,
  `idSuprimento` INT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `hora` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimentoSuprimento_farmaceutico1_idx` (`idFarmaceutico` ASC) VISIBLE,
  INDEX `fk_movimentoSuprimento_suprimento1_idx` (`idSuprimento` ASC) VISIBLE,
  CONSTRAINT `fk_movimentoSuprimento_farmaceutico1`
    FOREIGN KEY (`idFarmaceutico`)
    REFERENCES `mydb`.`farmaceutico` (`idProfissionalSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentoSuprimento_suprimento1`
    FOREIGN KEY (`idSuprimento`)
    REFERENCES `mydb`.`suprimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anamneseFeminina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anamneseFeminina` (
  `idAnamnese` INT NOT NULL,
  `anticoncepcional` TINYINT NULL,
  `tipoAnticoncepcional` INT NULL,
  `cicloMenstrual` INT NULL,
  INDEX `fk_anamneseFeminina_anamnese1_idx` (`idAnamnese` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
