/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.Enfermeiro;
import classes.HistoricoInternacao;
import classes.PrescricaoInternacao;
import classes.Suprimento;
import controles.ControleHistoricoInternacao;
import controles.ControleSuprimento;
import enums.TipoSuprimento;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Amanda
 */
public class TelaSolicitarSuprimentos extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialAdministrador
     */
    
    String dataConvertida, horaFormatada;
    DefaultTableModel suprimentosSolicitados;
    Enfermeiro enfermeiro;
    ControleSuprimento controleSuprimento = new ControleSuprimento();
    PrescricaoInternacao prescricao;
    ControleHistoricoInternacao controleHistorico = new ControleHistoricoInternacao();
    
    public TelaSolicitarSuprimentos(Enfermeiro enfermeiro, PrescricaoInternacao prescricao, 
            String nomePaciente, String nomeMedico, int leito) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.enfermeiro = enfermeiro;
        this.prescricao = prescricao;
        
        LocalDate hoje = LocalDate.now();
        LocalTime hora = LocalTime.now();
        DateTimeFormatter formataData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        dataConvertida = hoje.format(formataData);
        horaFormatada = hora.getHour() + ":" + hora.getMinute();
        
        this.nomePaciente.setText(nomePaciente);
        this.nomeMedico.setText(nomeMedico);
        this.numLeito.setText("" + leito);
        this.prescricaoMedica.setText(this.prescricao.getPrescricao());
        this.orientacoes.setText(this.prescricao.getOrientacoes());
        
        suprimentosSolicitados = (DefaultTableModel) tabelaSuprimentos.getModel();
        
        preencherNomeSuprimentos();
        preencheTipoSuprimento();
        desativaCampos();
        centralizarTextos();
        numEstoque.removeAllItems();
    }
    
    private void preencherNomeSuprimentos(){
        nomeSuprimentos.removeAllItems();
        ArrayList<Suprimento> suprimentos = controleSuprimento.recuperaSuprimentos(enfermeiro.getIdAdministracao());
        if(suprimentos != null){
            for(Suprimento s : suprimentos){
                nomeSuprimentos.addItem(s.getNome());
            }
        }
    }
    
    private void desativaCampos(){
        nomePaciente.setEditable(false);
        nomeMedico.setEditable(false);
        numLeito.setEditable(false);
        prescricaoMedica.setEditable(false);
        orientacoes.setEditable(false);
        listaTipoSuprimento.setEnabled(false);
        valorUnitario.setEnabled(false);
        numEstoque.setEnabled(false);
    }
    
    private void preencheTipoSuprimento(){
        listaTipoSuprimento.removeAllItems();
        for(TipoSuprimento ts : TipoSuprimento.values()){
            listaTipoSuprimento.addItem(ts.getTipoSuprimento());
        }
    }
    
    private void centralizarTextos(){
        DefaultTableCellRenderer centralizar = new DefaultTableCellRenderer();
        centralizar.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tabelaSuprimentos.getColumnCount(); i++) {
            tabelaSuprimentos.getColumnModel().getColumn(i).setCellRenderer(centralizar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSuprimentos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        listaTipoSuprimento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        valorUnitario = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        voltar = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        nomeSuprimentos = new javax.swing.JComboBox<>();
        numEstoque = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        nomePaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nomeMedico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numLeito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        prescricaoMedica = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orientacoes = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        finalizar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Leito");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Suprimentos");

        tabelaSuprimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSuprimentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaSuprimentos);
        if (tabelaSuprimentos.getColumnModel().getColumnCount() > 0) {
            tabelaSuprimentos.getColumnModel().getColumn(0).setResizable(false);
            tabelaSuprimentos.getColumnModel().getColumn(0).setPreferredWidth(250);
            tabelaSuprimentos.getColumnModel().getColumn(1).setResizable(false);
            tabelaSuprimentos.getColumnModel().getColumn(1).setPreferredWidth(250);
            tabelaSuprimentos.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setText("Nome do Suprimento:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo:");

        listaTipoSuprimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Valor Unitário:");

        jLabel5.setText("Estoque:");

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        nomeSuprimentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        numEstoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Paciente:");

        jLabel7.setText("Médico:");

        jLabel8.setText("Leito: ");

        jLabel9.setText("Prescrição:");

        prescricaoMedica.setColumns(20);
        prescricaoMedica.setRows(5);
        jScrollPane2.setViewportView(prescricaoMedica);

        jLabel10.setText("Orientações:");

        orientacoes.setColumns(20);
        orientacoes.setRows(5);
        jScrollPane3.setViewportView(orientacoes);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Solicitação de Suprimentos");

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu3.add(logout);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu3.add(sair);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaTipoSuprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numEstoque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeSuprimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numLeito, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(voltar)
                        .addGap(623, 623, 623)
                        .addComponent(finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(numLeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeSuprimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(listaTipoSuprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(valorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(numEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(adicionar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(finalizar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        new TelaInicialEnfermeiro(enfermeiro).setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        // TODO add your handling code here:
        
        String tipo = listaTipoSuprimento.getItemAt(listaTipoSuprimento.getSelectedIndex());
        String nomeSuprimento = nomeSuprimentos.getItemAt(nomeSuprimentos.getSelectedIndex());
        String valor = valorUnitario.getText();
        int quantEstoque = Integer.parseInt(numEstoque.getItemAt(numEstoque.getSelectedIndex()));
        
        System.out.println("Item -> " + nomeSuprimento + ", " + tipo + ", " + valor + ", " + quantEstoque);
        
        suprimentosSolicitados.addRow(new Object[]{
            nomeSuprimento,
            tipo,
            quantEstoque
        });
        
        preencheTipoSuprimento();
        preencherNomeSuprimentos();
        valorUnitario.setText("");
        numEstoque.removeAllItems();
        
    }//GEN-LAST:event_adicionarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        
        int index = nomeSuprimentos.getSelectedIndex();
        String nomeSuprimento = nomeSuprimentos.getItemAt(index);
        
        System.out.println("Nome Suprimento -> " + nomeSuprimento);
        
        Suprimento suprimento = controleSuprimento.buscaSuprimentoPorNome(nomeSuprimento);
        
        listaTipoSuprimento.setSelectedIndex(suprimento.getTipo());
        
        valorUnitario.setText("R$ " + suprimento.getValorUnitario());
        valorUnitario.setEnabled(true);
        valorUnitario.setEditable(false);
        
        numEstoque.setEnabled(true);
        numEstoque.removeAllItems();
        
        for(int i = 1; i < suprimento.getQuantidadeEstoque(); i++){
            numEstoque.addItem("" + i);
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
        
        String suprimentos = "";
        
        if(tabelaSuprimentos.getRowCount() != 0){
            for (int i = 0; i < tabelaSuprimentos.getRowCount(); i++){
                suprimentos = suprimentos + tabelaSuprimentos.getValueAt(i, 0) + "/"
                + tabelaSuprimentos.getValueAt(i, 1) + "/"
                + tabelaSuprimentos.getValueAt(i, 2) + "\n";
                
            }
        }
        
        HistoricoInternacao historicoInternacao = new HistoricoInternacao(prescricao.getId(), enfermeiro.getId(),
                dataConvertida, horaFormatada, suprimentos);
        
        String linhas[] = historicoInternacao.getSuprimentos().split("\n");
        System.out.println(linhas.length);
        
        for(int i = 0; i < linhas.length; i++){
            System.out.println(linhas[i]);
        }
        
        boolean confirmacao = controleHistorico.solicitacaoSuprimentos(historicoInternacao);
        
        if(confirmacao){
            JOptionPane.showMessageDialog(null, "Solicitações de Suprimentos enviado!");
            new TelaInicialEnfermeiro(enfermeiro).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Ops! Algo deu errado.");
        }
        
    }//GEN-LAST:event_finalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JButton buscar;
    private javax.swing.JButton finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> listaTipoSuprimento;
    private javax.swing.JMenuItem logout;
    private javax.swing.JTextField nomeMedico;
    private javax.swing.JTextField nomePaciente;
    private javax.swing.JComboBox<String> nomeSuprimentos;
    private javax.swing.JComboBox<String> numEstoque;
    private javax.swing.JTextField numLeito;
    private javax.swing.JTextArea orientacoes;
    private javax.swing.JTextArea prescricaoMedica;
    private javax.swing.JMenuItem sair;
    private javax.swing.JTable tabelaSuprimentos;
    private javax.swing.JFormattedTextField valorUnitario;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
