/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.Administracao;
import controles.ControleProfissional;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amanda
 */
public class TelaMedicosCadastrados extends javax.swing.JFrame {
    /**
     * Creates new form TelaAdministrador
     */
    
    Administracao adm;
    DefaultTableModel modeloLista;
    ControleProfissional controleProfissional = new ControleProfissional();
    
    public TelaMedicosCadastrados(Administracao adm) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.adm = adm;
        
        modeloLista = (DefaultTableModel) listaMedicos.getModel();
    }
    
    private void preencheTabela(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMedicos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        gerenciar = new javax.swing.JMenu();
        leitos = new javax.swing.JMenu();
        cadastrarLeito = new javax.swing.JMenuItem();
        suprimentos = new javax.swing.JMenu();
        novoSuprimento = new javax.swing.JMenuItem();
        internacoes = new javax.swing.JMenu();
        verificarInternacoes = new javax.swing.JMenuItem();
        pacientes = new javax.swing.JMenu();
        cadastrarPaciente = new javax.swing.JMenuItem();
        recursosHumanos = new javax.swing.JMenu();
        medicos = new javax.swing.JMenu();
        novoMedico = new javax.swing.JMenuItem();
        medicosCadastrados = new javax.swing.JMenuItem();
        enfermeiros = new javax.swing.JMenu();
        novoEnfermeiro = new javax.swing.JMenuItem();
        farmaceuticos = new javax.swing.JMenu();
        novoFarmaceutico = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Médicos Cadastrados nessa Unidade");

        listaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CRM/UF", "Telefone", "E-mail", "Contratação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaMedicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(listaMedicos);
        if (listaMedicos.getColumnModel().getColumnCount() > 0) {
            listaMedicos.getColumnModel().getColumn(0).setResizable(false);
            listaMedicos.getColumnModel().getColumn(0).setPreferredWidth(200);
            listaMedicos.getColumnModel().getColumn(1).setResizable(false);
            listaMedicos.getColumnModel().getColumn(2).setResizable(false);
            listaMedicos.getColumnModel().getColumn(3).setResizable(false);
            listaMedicos.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Voltar");
        jButton1.setHideActionText(true);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("Geral");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        gerenciar.setText("Gerenciamento Hospitalar");

        leitos.setText("Leitos");

        cadastrarLeito.setText("Cadastrar");
        cadastrarLeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLeitoActionPerformed(evt);
            }
        });
        leitos.add(cadastrarLeito);

        gerenciar.add(leitos);

        suprimentos.setText("Suprimentos");

        novoSuprimento.setText("Novo Suprimento");
        novoSuprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoSuprimentoActionPerformed(evt);
            }
        });
        suprimentos.add(novoSuprimento);

        gerenciar.add(suprimentos);

        internacoes.setText("Internações");

        verificarInternacoes.setText("Verificar Internações");
        internacoes.add(verificarInternacoes);

        gerenciar.add(internacoes);

        pacientes.setText("Pacientes");

        cadastrarPaciente.setText("Cadastrar Paciente");
        cadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPacienteActionPerformed(evt);
            }
        });
        pacientes.add(cadastrarPaciente);

        gerenciar.add(pacientes);

        jMenuBar1.add(gerenciar);

        recursosHumanos.setText("Recursos Humanos");

        medicos.setText("Médicos");

        novoMedico.setText("Novo Médico");
        novoMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoMedicoActionPerformed(evt);
            }
        });
        medicos.add(novoMedico);

        medicosCadastrados.setText("Médicos Cadastrados");
        medicos.add(medicosCadastrados);

        recursosHumanos.add(medicos);

        enfermeiros.setText("Enfermeiros");

        novoEnfermeiro.setText("Novo Enfermeiro");
        novoEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEnfermeiroActionPerformed(evt);
            }
        });
        enfermeiros.add(novoEnfermeiro);

        recursosHumanos.add(enfermeiros);

        farmaceuticos.setText("Farmacêuticos");

        novoFarmaceutico.setText("Novo Farmacêutico");
        novoFarmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoFarmaceuticoActionPerformed(evt);
            }
        });
        farmaceuticos.add(novoFarmaceutico);

        recursosHumanos.add(farmaceuticos);

        jMenuBar1.add(recursosHumanos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sairMouseClicked

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void novoSuprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoSuprimentoActionPerformed
        // TODO add your handling code here:
        new TelaCadastroSuprimento(adm).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoSuprimentoActionPerformed

    private void cadastrarLeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLeitoActionPerformed
        // TODO add your handling code here:
        new TelaCadastroLeito(adm).setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarLeitoActionPerformed

    private void novoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoMedicoActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarMedico(adm).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoMedicoActionPerformed

    private void novoEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoEnfermeiroActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarEnfermeiro(adm).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoEnfermeiroActionPerformed

    private void novoFarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoFarmaceuticoActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarFarmaceutico(adm).setVisible(true);
        dispose();
    }//GEN-LAST:event_novoFarmaceuticoActionPerformed

    private void cadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPacienteActionPerformed
        // TODO add your handling code here:
        new TelaCadastrarPaciente(adm).setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarPacienteActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarLeito;
    private javax.swing.JMenuItem cadastrarPaciente;
    private javax.swing.JMenu enfermeiros;
    private javax.swing.JMenu farmaceuticos;
    private javax.swing.JMenu gerenciar;
    private javax.swing.JMenu internacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu leitos;
    private javax.swing.JTable listaMedicos;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu medicos;
    private javax.swing.JMenuItem medicosCadastrados;
    private javax.swing.JMenuItem novoEnfermeiro;
    private javax.swing.JMenuItem novoFarmaceutico;
    private javax.swing.JMenuItem novoMedico;
    private javax.swing.JMenuItem novoSuprimento;
    private javax.swing.JMenu pacientes;
    private javax.swing.JMenu recursosHumanos;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenu suprimentos;
    private javax.swing.JMenuItem verificarInternacoes;
    // End of variables declaration//GEN-END:variables
}
