/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.Agenda;
import classes.Medico;
import classes.Paciente;
import controles.ControleAgenda;
import controles.ControleMedico;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amanda
 */
public class TelaInicialMedico extends javax.swing.JFrame {

    String dataConvertida;
    Medico medico;
    DefaultTableModel consultasDoDia;
    ControleMedico controleMedico = new ControleMedico();
    ControleAgenda controleAgenda = new ControleAgenda();
    String nomePaciente = "";
    String hora = "";
    
    /**
     * Creates new form TelaInicialAdministrador
     */
    public TelaInicialMedico(Medico medico){
        initComponents();
        this.setLocationRelativeTo(null);
        this.medico = medico;
        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formataData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        dataConvertida = hoje.format(formataData);
        this.nomeDr.setText("Seja Bem-vindo Drº " + this.medico.getNome());
        this.dataAtual.setText("Data: " + dataConvertida);
        
        consultasDoDia = (DefaultTableModel) consultasDia.getModel();
        
        preencheConsultasdoDia();
        centralizarTextos();
    }
    
    private void preencheConsultasdoDia(){
        consultasDoDia.setRowCount(0);
        ArrayList<Agenda> agendaDoDia = controleMedico.consultasDoDia(dataConvertida, medico);
        if(agendaDoDia != null){
            for(Agenda a : agendaDoDia){
                Paciente paciente = controleMedico.buscaPacientePorID(a.getIdPaciente());
                consultasDoDia.addRow(new Object[]{a.getHora(),paciente.getNome()});
            }
        }
    }
    
    private void centralizarTextos(){
        DefaultTableCellRenderer centralizar = new DefaultTableCellRenderer();
        centralizar.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < consultasDia.getColumnCount(); i++) {
            consultasDia.getColumnModel().getColumn(i).setCellRenderer(centralizar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        nomeDr = new javax.swing.JLabel();
        dataAtual = new javax.swing.JLabel();
        iniciarConsulta = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consultasDia = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        agendaCompleta = new javax.swing.JMenuItem();
        addNovasDatas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        solicitacoesInternacao = new javax.swing.JMenuItem();
        verificarInternacoes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeDr.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nomeDr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomeDr.setText("Label Bem Vindo Dr.");

        dataAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataAtual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dataAtual.setText("Label da Data Atual");

        iniciarConsulta.setText("Iniciar Consulta");
        iniciarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarConsultaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Consultas Agendadas para Hoje");

        consultasDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Horário", "Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        consultasDia.getTableHeader().setReorderingAllowed(false);
        consultasDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultasDiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(consultasDia);
        if (consultasDia.getColumnModel().getColumnCount() > 0) {
            consultasDia.getColumnModel().getColumn(0).setResizable(false);
            consultasDia.getColumnModel().getColumn(0).setPreferredWidth(1);
            consultasDia.getColumnModel().getColumn(1).setResizable(false);
            consultasDia.getColumnModel().getColumn(1).setPreferredWidth(180);
        }

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu3.add(logout);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu3.add(sair);

        jMenuBar2.add(jMenu3);

        jMenu1.setText("Minha Agenda");

        agendaCompleta.setText("Agenda Completa");
        agendaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaCompletaActionPerformed(evt);
            }
        });
        jMenu1.add(agendaCompleta);

        addNovasDatas.setText("Adicionar Novas Datas");
        addNovasDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNovasDatasActionPerformed(evt);
            }
        });
        jMenu1.add(addNovasDatas);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Internações");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        solicitacoesInternacao.setText("Solicitações");
        jMenu2.add(solicitacoesInternacao);

        verificarInternacoes.setText("Verificar Internações");
        verificarInternacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarInternacoesActionPerformed(evt);
            }
        });
        jMenu2.add(verificarInternacoes);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeDr, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(dataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addComponent(iniciarConsulta)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(nomeDr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataAtual)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarConsulta)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void addNovasDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNovasDatasActionPerformed
        // TODO add your handling code here:
        new TelaCadastroDatasConsultas(medico).setVisible(true);
        dispose();
    }//GEN-LAST:event_addNovasDatasActionPerformed

    private void agendaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaCompletaActionPerformed
        // TODO add your handling code here:
        new TelaAgendaCompleta(medico).setVisible(true);
        dispose();
    }//GEN-LAST:event_agendaCompletaActionPerformed

    private void iniciarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarConsultaActionPerformed
        // TODO add your handling code here:
        
        if(nomePaciente.isBlank()){
            JOptionPane.showMessageDialog(null, "Nenhuma consulta selecionada!");
        } else {
            Paciente paciente = controleMedico.buscaPacientePorNome(nomePaciente);
            Agenda agenda = controleAgenda.retornaAgenda(dataConvertida, hora, paciente.getId());
            new TelaAnamnesePaciente(medico, paciente,agenda).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_iniciarConsultaActionPerformed

    private void consultasDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultasDiaMouseClicked
        // TODO add your handling code here:
        int linha = consultasDia.getSelectedRow();
        
        hora = String.valueOf(consultasDia.getValueAt(linha, 0));
        nomePaciente = String.valueOf(consultasDia.getValueAt(linha, 1));
        
        System.out.println(hora + " -> " + nomePaciente);
    }//GEN-LAST:event_consultasDiaMouseClicked

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new TelaInicial().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void verificarInternacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarInternacoesActionPerformed
        // TODO add your handling code here:
        new TelaVerificarInternacoes(medico).setVisible(true);
        dispose();
    }//GEN-LAST:event_verificarInternacoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addNovasDatas;
    private javax.swing.JMenuItem agendaCompleta;
    private javax.swing.JTable consultasDia;
    private javax.swing.JLabel dataAtual;
    private javax.swing.JButton iniciarConsulta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JLabel nomeDr;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem solicitacoesInternacao;
    private javax.swing.JMenuItem verificarInternacoes;
    // End of variables declaration//GEN-END:variables
}
