-- MySQL Script generated by MySQL Workbench
-- Mon Jul 14 14:02:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vidaplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vidaplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vidaplus` DEFAULT CHARACTER SET utf8 ;
USE `vidaplus` ;

-- -----------------------------------------------------
-- Table `vidaplus`.`administracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`administracao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(20) NOT NULL,
  `razaoSocial` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `sexo` INT NOT NULL,
  `idAdministracao` INT NOT NULL,
  PRIMARY KEY (`id`, `idAdministracao`),
  INDEX `fk_paciente_administracao_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_administracao`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `vidaplus`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`profissionalSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`profissionalSaude` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAdministracao` INT NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `dataContratacao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profissionalSaude_administracao1_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_profissionalSaude_administracao1`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `vidaplus`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`medico` (
  `idProfissionalSaude` INT NOT NULL,
  `crm` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `dataInscricao` VARCHAR(10) NOT NULL,
  `especialidade` INT NOT NULL,
  INDEX `fk_medico_profissionalSaude1_idx` (`idProfissionalSaude` ASC) VISIBLE,
  PRIMARY KEY (`idProfissionalSaude`),
  CONSTRAINT `fk_medico_profissionalSaude1`
    FOREIGN KEY (`idProfissionalSaude`)
    REFERENCES `vidaplus`.`profissionalSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`enfermeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`enfermeiro` (
  `idProfissionalSaude` INT NOT NULL,
  `coren` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `dataEmissao` VARCHAR(10) NOT NULL,
  `tipo` INT NOT NULL,
  INDEX `fk_table1_profissionalSaude1_idx` (`idProfissionalSaude` ASC) VISIBLE,
  PRIMARY KEY (`idProfissionalSaude`),
  CONSTRAINT `fk_table1_profissionalSaude1`
    FOREIGN KEY (`idProfissionalSaude`)
    REFERENCES `vidaplus`.`profissionalSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`farmaceutico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`farmaceutico` (
  `idProfissionalSaude` INT NOT NULL,
  `crf` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `categoriaProfissional` INT NOT NULL,
  `dataExpedicao` VARCHAR(10) NOT NULL,
  INDEX `fk_table2_profissionalSaude1_idx` (`idProfissionalSaude` ASC) VISIBLE,
  PRIMARY KEY (`idProfissionalSaude`),
  CONSTRAINT `fk_table2_profissionalSaude1`
    FOREIGN KEY (`idProfissionalSaude`)
    REFERENCES `vidaplus`.`profissionalSaude` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`anamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`anamnese` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataAtualizacao` VARCHAR(10) NULL,
  `diabetes` TINYINT NULL,
  `hipertensao` TINYINT NULL,
  `hipotensao` TINYINT NULL,
  `tabagismo` TINYINT NULL,
  `epilepsia` TINYINT NULL,
  `proteseDentaria` TINYINT NULL,
  `problemasRespitatorios` TINYINT NULL,
  `anotacoesRespiratorias` VARCHAR(500) NULL,
  `cirurgias` TINYINT NULL,
  `anotacoesCirurgias` VARCHAR(500) NULL,
  `exerciciosFisicos` TINYINT NULL,
  `frequenciaExercicios` INT NULL,
  `alcool` TINYINT NULL,
  `frequenciaAlcool` INT NULL,
  `alergiaMedicacao` TINYINT NULL,
  `anotacoesAlergiasMedicamento` VARCHAR(500) NULL,
  `alergiaAlimento` TINYINT NULL,
  `anotacoesAlergiaAlimento` VARCHAR(500) NULL,
  `tratamentoAtual` TINYINT NULL,
  `anotacoesTratamento` VARCHAR(500) NULL,
  `marcaPasso` TINYINT NULL,
  `medicamentoContinuo` TINYINT NULL,
  `anotacoesMedicamentoContinuo` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`prontuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NOT NULL,
  `idAnamnese` INT NOT NULL,
  `dataAtualizacao` VARCHAR(10) NULL,
  `servico` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prontuario_paciente1_idx` (`idPaciente` ASC) VISIBLE,
  INDEX `fk_prontuario_anamnese1_idx` (`idAnamnese` ASC) VISIBLE,
  CONSTRAINT `fk_prontuario_paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `vidaplus`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prontuario_anamnese1`
    FOREIGN KEY (`idAnamnese`)
    REFERENCES `vidaplus`.`anamnese` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`suprimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`suprimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAdministracao` INT NOT NULL,
  `tipo` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `quantEstoque` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suprimento_administracao1_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_suprimento_administracao1`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `vidaplus`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`agenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idMedico` INT NOT NULL,
  `idPaciente` INT NULL,
  `data` VARCHAR(10) NOT NULL,
  `hora` VARCHAR(5) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agenda_medico1_idx` (`idMedico` ASC) VISIBLE,
  INDEX `fk_agenda_paciente1_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `vidaplus`.`medico` (`idProfissionalSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `vidaplus`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`consulta` (
  `idAgenda` INT NOT NULL,
  `idProntuario` INT NOT NULL,
  `queixa` VARCHAR(150) NOT NULL,
  `sintomas` VARCHAR(250) NOT NULL,
  `pressao` INT NOT NULL,
  `frequenciaCardiaca` INT NOT NULL,
  `temperatura` INT NOT NULL,
  `diagnostico` VARCHAR(150) NOT NULL,
  `prescricao` VARCHAR(300) NOT NULL,
  `observacoes` VARCHAR(200) NULL,
  INDEX `fk_consulta_agenda1_idx` (`idAgenda` ASC) VISIBLE,
  PRIMARY KEY (`idAgenda`),
  INDEX `fk_consulta_prontuario1_idx` (`idProntuario` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_agenda1`
    FOREIGN KEY (`idAgenda`)
    REFERENCES `vidaplus`.`agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_prontuario1`
    FOREIGN KEY (`idProntuario`)
    REFERENCES `vidaplus`.`prontuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`leito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`leito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAdministracao` INT NOT NULL,
  `tipoLeito` INT NOT NULL,
  `numero` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` INT NOT NULL,
  `capacidade` INT NOT NULL,
  `internados` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_leito_administracao1_idx` (`idAdministracao` ASC) VISIBLE,
  CONSTRAINT `fk_leito_administracao1`
    FOREIGN KEY (`idAdministracao`)
    REFERENCES `vidaplus`.`administracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`internacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`internacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idConsulta` INT NOT NULL,
  `idMedico` INT NOT NULL,
  `idLeito` INT NULL,
  `idProntuario` INT NOT NULL,
  `aguardandoAprovacao` TINYINT NOT NULL,
  `statusAlta` TINYINT NOT NULL,
  `observacoes` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_internacao_consulta1_idx` (`idConsulta` ASC) VISIBLE,
  INDEX `fk_internacao_medico1_idx` (`idMedico` ASC) VISIBLE,
  INDEX `fk_internacao_leito1_idx` (`idLeito` ASC) VISIBLE,
  INDEX `fk_internacao_prontuario1_idx` (`idProntuario` ASC) VISIBLE,
  CONSTRAINT `fk_internacao_consulta1`
    FOREIGN KEY (`idConsulta`)
    REFERENCES `vidaplus`.`consulta` (`idAgenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internacao_medico1`
    FOREIGN KEY (`idMedico`)
    REFERENCES `vidaplus`.`medico` (`idProfissionalSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internacao_leito1`
    FOREIGN KEY (`idLeito`)
    REFERENCES `vidaplus`.`leito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internacao_prontuario1`
    FOREIGN KEY (`idProntuario`)
    REFERENCES `vidaplus`.`prontuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`prescricaoInternacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`prescricaoInternacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idInternacao` INT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `prescricao` VARCHAR(200) NOT NULL,
  `orientacoes` VARCHAR(200) NULL,
  `observacoes` VARCHAR(300) NULL,
  `realizado` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prescricaoInternacao_internacao1_idx` (`idInternacao` ASC) VISIBLE,
  CONSTRAINT `fk_prescricaoInternacao_internacao1`
    FOREIGN KEY (`idInternacao`)
    REFERENCES `vidaplus`.`internacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`historicoInternacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`historicoInternacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idPrescricao` INT NOT NULL,
  `idEnfermeiro` INT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `hora` VARCHAR(5) NOT NULL,
  `suprimentos` VARCHAR(500) NOT NULL,
  `solicitacaoAtendida` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historicoInternacao_enfermeiro1_idx` (`idEnfermeiro` ASC) VISIBLE,
  INDEX `fk_historicoInternacao_prescricaoInternacao1_idx` (`idPrescricao` ASC) VISIBLE,
  CONSTRAINT `fk_historicoInternacao_enfermeiro1`
    FOREIGN KEY (`idEnfermeiro`)
    REFERENCES `vidaplus`.`enfermeiro` (`idProfissionalSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historicoInternacao_prescricaoInternacao1`
    FOREIGN KEY (`idPrescricao`)
    REFERENCES `vidaplus`.`prescricaoInternacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`movimentoSuprimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`movimentoSuprimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFarmaceutico` INT NOT NULL,
  `idSuprimento` INT NOT NULL,
  `idHistoricoInternacao` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `data` VARCHAR(10) NOT NULL,
  `hora` VARCHAR(5) NOT NULL,
  `entregue` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimentoSuprimento_farmaceutico1_idx` (`idFarmaceutico` ASC) VISIBLE,
  INDEX `fk_movimentoSuprimento_suprimento1_idx` (`idSuprimento` ASC) VISIBLE,
  INDEX `fk_movimentoSuprimento_historicoInternacao1_idx` (`idHistoricoInternacao` ASC) VISIBLE,
  CONSTRAINT `fk_movimentoSuprimento_farmaceutico1`
    FOREIGN KEY (`idFarmaceutico`)
    REFERENCES `vidaplus`.`farmaceutico` (`idProfissionalSaude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentoSuprimento_suprimento1`
    FOREIGN KEY (`idSuprimento`)
    REFERENCES `vidaplus`.`suprimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentoSuprimento_historicoInternacao1`
    FOREIGN KEY (`idHistoricoInternacao`)
    REFERENCES `vidaplus`.`historicoInternacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidaplus`.`anamneseFeminina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidaplus`.`anamneseFeminina` (
  `idAnamnese` INT NOT NULL,
  `anticoncepcional` TINYINT NULL,
  `tipoAnticoncepcional` INT NULL,
  `cicloMenstrual` INT NULL,
  INDEX `fk_anamneseFeminina_anamnese1_idx` (`idAnamnese` ASC) VISIBLE,
  PRIMARY KEY (`idAnamnese`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
